/**
 * GENERATED by `scripts/fetch-project-galleries.mjs` — do not hand-edit.
 *
 * The image half of the case-study content seam: `data.ts` owns the words,
 * this file owns the pictures. Each entry lists the images of the live
 * `[Imgaeproject]` column in scroll order, as filenames inside
 * `public/sites/huyml-co-eb36a18b/shared/` (resolve them with `assetUrl`).
 *
 * Re-run the script after adding a project, or replace the files with your own
 * artwork and keep the names — the page renders `gallery.length` frames.
 */
export const PROJECT_GALLERIES: Readonly<Record<string, readonly string[]>> = {
  "biy": ["biy-01.png", "biy-02.png", "biy-03.png"],
  "district2-studio": ["unicom-5g-cover.png"],
  "telecom-5g-series": [
    "telecom-5g-01.jpg",
    "telecom-5g-02.jpg",
    "telecom-5g-03.jpg",
    "telecom-5g-04.jpg",
    "telecom-5g-05.png",
  ],
  "juner-carl": [
    "juner-carl-07.jpg",
    "juner-carl-08.jpg",
    "juner-carl-09.jpg",
    "juner-carl-01.jpg",
    "juner-carl-02.jpg",
    "juner-carl-03.jpg",
    "juner-carl-04.jpg",
    "juner-carl-05.jpg",
    "juner-carl-06.jpg",
  ],
  "valentines-day": [
    "valentines-day-01.jpg",
    "valentines-day-02.jpg",
    "valentines-day-03.png",
  ],
  "yaojin-brand": ["yaojin-brand-01.jpg"],
  "grow-more-program": [
    "grow-more-01.jpg",
    "grow-more-02.jpg",
    "grow-more-03.jpg",
  ],
  "street-photography": [
    "street-photo-01.jpg",
    "street-photo-02.jpg",
    "street-photo-03.jpg",
  ],
  "credit-app-ui": [
    "credit-app-ui-01.png",
    "credit-app-ui-02.jpg",
    "credit-app-ui-03.jpg",
    "credit-app-ui-04.jpg",
  ],
  "fairway-editorial": [
    "fairway-editorial-01.jpg",
    "fairway-editorial-02.jpg",
    "fairway-editorial-03.jpg",
  ],
  "materialism-necklace": ["materialism-01.jpg"],
  "ear-manual": [
    "ear-manual-01.jpg",
    "ear-manual-02.jpg",
    "ear-manual-03.jpg",
    "ear-manual-04.jpg",
    "ear-manual-05.jpg",
    "ear-manual-06.jpg",
  ],
  "eislab": ["Qz7IA3cxk2ytInSo2iqoxwkYzX0.jpg", "gfhG39T9bYBENJqrSSgCfM6cxI.jpg", "rD5C15OquIbYHQUP4pXqzXE2tOk.jpg", "KYrg5rmo9Uq2YPlyEw6A1f6v2s.jpg", "GpawisL3wLgB9HEXcuqeClcuXo.jpg", "UR9JFWMLOnwxdJNFm49YJjZdxKg.jpg", "V5EglSa4L79VSjnPEJH3W393HMo.jpg", "uL7t9GVoMh0BJNmFAI1pgijSrqA.jpg"],
};
