import fs from "node:fs";
import path from "node:path";

// WARNING: running this rewrites `data.ts`. Only ever point it at the page that
// owns `data.ts` (the home page); never run it for a case-study page.
const root = process.argv[2] || "docs/research/huyml-co-eb36a18b/root-8a5edab2";
const { archive, selected } = JSON.parse(fs.readFileSync(path.join(root, "projects.json"), "utf8"));

const assetBase = "/sites/huyml-co-eb36a18b/shared/";

// Palettes for the "Selected work" wheel. The live site swaps these via JS, so the
// values below are the ones observed in the DOM / derived from the matching archive
// entry (Mathijs Hanenkamp) and complementary palettes for the remaining cards.
const wheelPalettes = [
  ["rgb(34, 34, 34)", "rgb(240, 240, 240)", "rgb(255, 0, 0)"],
  ["rgb(20, 20, 20)", "rgb(227, 232, 236)", "rgb(206, 255, 69)"],
  ["rgb(229, 227, 219)", "rgb(33, 33, 37)", "rgb(255, 90, 54)"],
  ["rgb(15, 15, 15)", "rgb(186, 55, 55)", "rgb(255, 255, 255)"],
  ["rgb(0, 153, 255)", "rgb(7, 7, 7)", "rgb(26, 44, 70)"],
  ["rgb(18, 18, 18)", "rgb(255, 255, 255)", "rgb(214, 214, 214)"],
  ["rgb(251, 193, 212)", "rgb(195, 171, 255)", "rgb(252, 248, 236)"],
  ["rgb(5, 18, 54)", "rgb(255, 253, 226)", "rgb(4, 87, 212)"],
];

const wheel = selected.map((s, i) => ({ ...s, colors: wheelPalettes[i] ?? wheelPalettes[0] }));

/**
 * All copy below is transcribed verbatim from the live DOM
 * (`data-framer-name` layers and their text nodes), at the desktop breakpoint.
 * Hrefs come from the same nodes, so the contact / credits cards are exact.
 */
const site = {
  owner: "Huy Phan",
  ownerAlias: "Hon Tran",
  year: "2023",
  role: "Independent designer",
  email: "xkt202311@163.com",
  launchLabel: "Launch",
  recognitionLabel: "Recognition",
  scrollLabel: "Scroll",
  selectedLabel: "Selected work",
  counterTotal: "/00",
  menuLabel: "Menu",
  inquiriesLabel: "For inquiries",
  copyLabel: "Click to copy",
  copiedLabel: "Copied",
  showreelLabel: "'25 showreel",
  closeLabel: "Close",
  contactTitle: "Come say hi",
  ownerLines: ["Independent designer", "Working globally"],
  contactGroups: [
    {
      caption: "Drop me a line",
      links: [{ label: "xkt202311@163.com", href: "mailto:xkt202311@163.com" }],
    },
    {
      caption: "Hear me yapping about design",
      links: [{ label: "YouTube", href: "https://www.youtube.com/@huyml.studio" }],
    },
    {
      caption: "More design stuff",
      links: [
        { label: "Behance", href: "https://www.behance.net/huyphan2602" },
        { label: "Dribbble", href: "https://dribbble.com/huyphan2602" },
      ],
    },
    {
      caption: "Design & life updates lately",
      links: [
        { label: "LinkedIn", href: "https://www.linkedin.com/in/huy-phan-086023a5" },
        { label: "Instagram", href: "https://www.instagram.com/huy.phan.2602" },
        { label: "Facebook", href: "https://www.facebook.com/phan.huy.2602" },
      ],
    },
    {
      caption: "Things I captured along the way",
      links: [
        { label: "Unsplash", href: "https://unsplash.com/@huyphan2602" },
        { label: "Pexels", href: "https://www.pexels.com/@huy-phan-316220" },
      ],
    },
  ],
  creditsTitle: "Credits",
  credits: [
    {
      role: "Development & Rive",
      people: [{ label: "Chien Pham", href: "https://x.com/BausPjam" }],
    },
    {
      role: "Illustration",
      people: [{ label: "Yup Nguyen", href: "https://dribbble.com/yupnguyen" }],
    },
    {
      role: "Fonts",
      people: [
        {
          label: "BT Glyphius",
          href: "https://www.myfonts.com/collections/bt-glyphius-font-bitstream",
        },
        {
          label: "BT Grotesk",
          href: "https://www.myfonts.com/collections/bt-grotesk-font-bitstream",
        },
      ],
    },
    {
      role: "Copywriting",
      people: [{ label: "Ha Nguyen (the wife)", href: "https://www.youtube.com/@theimpulsivestitch" }],
    },
  ],
  heroRecognition: ["FWA of the Day", "CSSDA Website of the Day", "Behance UI Gallery"],
};

/** `framer-1irp2nk` / `framer-151iacu` — the same four rows in both nav surfaces. */
const nav = [
  { label: "WORK", href: "#work" },
  { label: "ABOUT", href: "#about" },
  { label: "PLAYGROUND", href: "#playground" },
  { label: "CONTACT", href: "#contact" },
];

const ts = `/**
 * Verbatim content extracted from https://huyml.co/ (desktop / 1440px).
 * Generated by scripts/gen-data.mjs — do not hand-edit.
 */

export type ArchiveColors = readonly string[];

export interface ArchiveEntry {
  readonly slug: string;
  readonly title: string;
  readonly date: string;
  readonly dateLabel: string;
  readonly colors: ArchiveColors;
  readonly recognition: readonly string[];
  readonly roles: readonly string[];
  readonly ruler: readonly string[];
  readonly category: string;
  readonly description: string;
  readonly image: string;
}

export interface SelectedWork {
  readonly title: string;
  readonly tag: string;
  readonly description: string;
  readonly colors: ArchiveColors;
}

export interface ContactLink {
  readonly label: string;
  readonly href: string;
}

export interface SocialGroup {
  readonly caption: string;
  readonly links: readonly ContactLink[];
}

export interface CreditRow {
  readonly role: string;
  readonly people: readonly ContactLink[];
}

export interface NavItem {
  readonly label: string;
  readonly href: string;
}

export interface SiteMeta {
  readonly owner: string;
  readonly ownerAlias: string;
  readonly year: string;
  readonly role: string;
  readonly email: string;
  readonly launchLabel: string;
  readonly recognitionLabel: string;
  readonly scrollLabel: string;
  readonly selectedLabel: string;
  readonly counterTotal: string;
  readonly menuLabel: string;
  readonly inquiriesLabel: string;
  readonly copyLabel: string;
  readonly copiedLabel: string;
  readonly showreelLabel: string;
  readonly closeLabel: string;
  readonly contactTitle: string;
  readonly ownerLines: readonly string[];
  readonly contactGroups: readonly SocialGroup[];
  readonly creditsTitle: string;
  readonly credits: readonly CreditRow[];
  readonly heroRecognition: readonly string[];
}

export const SITE: SiteMeta = ${JSON.stringify(site, null, 2)};

export const NAV: readonly NavItem[] = ${JSON.stringify(nav, null, 2)};

export const WHEEL: readonly SelectedWork[] = ${JSON.stringify(wheel, null, 2)} as const;

export const ARCHIVE: readonly ArchiveEntry[] = ${JSON.stringify(archive, null, 2)} as const;

export const assetUrl = (file: string): string => \`${assetBase}\${file}\`;

/** The four faces of the rotating logo stamp pinned to the top-left of the canvas. */
export const STAMP_FACES: readonly string[] = [
  "R4RlD3IldAw8k5cRONJ8SJJgqG4.svg",
  "Bi57PSNgEGNhXnUjCjYBKAacRQ.svg",
  "EwHniTuZoV3ME15lpjBiKTAYilc.svg",
  "JZyDNnSPROUpFuFHbWYIKApoHng.svg",
];
`;

const outPath = "src/components/sites/huyml-co-eb36a18b/root-8a5edab2/data.ts";
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, ts, "utf8");
console.log("wrote", outPath, ts.length, "chars; archive:", archive.length, "wheel:", wheel.length);
